version: '2'

services:
  crystal:
    image: crystallang/crystal:1.6.2-alpine
    command: shards build --link-flags "-static"
    user: "${UID}:${GID}"
    volumes:
      - .:/v
    working_dir: /v
